### PR TITLE
Keyboard - Fix enter not closing the dropdown menu on selection

### PR DESCRIPTION
**Pull request by BARNZ**
Another thing found during testing. When an item is focused with the keyboard and enter is pressed it would select the item, however this bit of code in the watcher would unexpectedly re-open the list again.

I feel UX is improved a little by hiding the dropdown list after a selection is made with the keyboard.

### CODE REVIEW

**Comment by mattzollinhofer** [comment]
This one I'm a little less sure about. I can see a case where this is nice, but I'm not sure I want that to be the default behavior. Somewhat of a work around is that you can use `@hit` to clear the input's value which would also close the dropdown. I'd also consider adding a method that can be called to explicitly close the dropdown if it's open.

Let me think about this one for a bit.

**Comment by BozoJim** [comment]
I think in most cases we do want the dropdown to close, that is typical of most dropdowns. You click the option, it does a thing, and gets out of your way.
I can see adding an optional flag to keep it open though, if you were to use the dropdown as a multi-select for example.

**Comment by mattzollinhofer** [comment]
Yeah, after thinking about it I do tend to agree. I think just deleting those lines will break some of the keyboard navigation cases (although I'm not positive which ones). I _think_ something to do with hitting `esc` or maybe `tab`.

**Comment by mattzollinhofer** [comment]
Ok, I finally found the specific problem this suggested change brings up. 

Replication steps:
- at the main example page (http://localhost:8080)
- type "can".  You're presented a few possible matches (canada, american samoa, etc)
- arrow down once. (selecting "canada")
- hit escape. 

**undesired outcome**: this will not only close the dropdown, but also clear the text you've typed. 

When you hit escape, you really only want the dropdown to close, not to remove the text. But if you hit escape a second time (once to close the dropdown) you'd expect the text to clear. The commit message for 68296d5adf987b13228bf089c9255784b2bd396d outlines a few different cases to consider.

@BARNZ, do you think this is something you'd be able to take into account? 

(sorry it took me a while to get back to this, been a bit distracted with covid and all that...)

**Comment by BARNZ** [comment]
Hey @mattzollinhofer I have opened another pull request #29 which fixes this specific behavior.

I plan to instead update this pull request with the ability to configure the close on enter behavior via a config option as suggested by @BozoJim

**Comment by BARNZ** [comment]
Closed in favor of #31

**Pull request closed without merging**
