### PR TITLE
add accents support

### PR DESCRIPTION
**Pull request by eduardosada**
Enable locale text comparison for spanish language.

### CODE REVIEW

**Comment by yobuntu** [comment]
That looks very good to me, 
I'm not familiar with `return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '')`, is it specific for spanish language or is this work for most of european accent ?

**Comment by eduardosada** [comment]
Is not only for spanish. It works with any unicode character.

```
'associação'.normalize('NFD').replace(/[\u0300-\u036f]/g, '') === 'associacao'
```

`ç` and `ã` doesn't exist in spanish language.

I need this so for a list with an item like `Médicos` the user is expecting that item when they write `med`.

**Comment by mattzollinhofer** [comment]
Sorry I was a little slow to respond. I put some comments on another PR (#85) so that I could share a new test. Take a look and let me know what you think.

**Comment by mattzollinhofer** [comment]
Closing as this was resolved in #100. Thanks for the help!

**Pull request closed without merging**
