### PR TITLE
Update package.json version to 2.13.0

### PR DESCRIPTION
**Pull request by drikusroor**

### CODE REVIEW

**Comment by darrinmn9** [comment]
@drikusroor I dont think `v2.13.0` was ever released to npm/yarn. https://www.npmjs.com/package/vue-typeahead-bootstrap (still says version `2.12.0`). Attempting to install on yarn gives me a prompt that `2.13.0` does not exist

**Comment by drikusroor** [comment]
@darrinmn9 that is correct, I have not been given access to the NPM package yet and therefore I cannot create a release. 😞 @mattzollinhofer could you create a release on NPM or give me access? (Putting some pressure on you now 😸)

**Comment by darrinmn9** [comment]
@drikusroor is it worth updating this repo's README to reference that https://github.com/drikusroor/vue-bootstrap-autocomplete is a continuation of this project?

**Comment by drikusroor** [comment]
@darrinmn9 Yes, that would definitely be worth it. I haven't heard from @mattzollinhofer in a while - we discussed notifying people of the continuation of this project over email - but perhaps we could create a PR for updating the readme of this repository.

**Pull request merged**
