### PR TITLE
Feature - list append slot

### PR DESCRIPTION
**Pull request by themeler**
Additional slot, when used, appends list item to autocomplete list. Emits `hitListAppend` event with query on click, For example, you can use it to add non existing resource (using query).

Really need this feature and workarounds are terrible to use, so I've added it and hope everyone will make use of it.

Docs and tests updated.

### CODE REVIEW

**Comment by mattzollinhofer** [comment]
This looks like a great PR. I'll hopefully have a chance to look at it more closely this coming week.

**Review by mattzollinhofer — CHANGES_REQUESTED** [review]
A few thoughts come to mind.

### Great PR!
A HUGE thank you for the example you included. I had the wrong idea about what you were going for until I looked at the example. That really helped. 

Another thank you for a really thorough and thoughtful PR, even updating the version number. Wonderful!

### Accessibility impact
One of my biggest focuses when taking over this project was to do as best I could with providing an accessible component. I'm not sure it's perfect, but I'm trying really hard at that. 

With that said, I'm afraid these changes don't behave as I'd expect for keyboard only users. My expectation is that anything in the list is actionable by a keyboard user using the arrow and enter keys. But when I use down arrow after typing `re` I can't get down to the appended item.

Additionally, the combination of `tabIndex=0` and `aria-hidden` is a little confusing (without the accompanying `sr-only` text) and I'd imagine would make it so that  a screen reader wouldn't read this item to the user.

I'm open to thoughts on this. 

### The Use Case
I haven't thought through this completely, but I'm not sure I totally think the additional slot is necessary for the example provided. It seems possible to update the data being provided to the typeahead with an additional value (even as the user types) to provide an entry that says "add: re" (in my case). I believe I've done this in the past. Given the non-obvious accessibility implications, I'm a little hesitant to include this without some more understanding. 

You mentioned that the work around(s) are terrible. Do you mind describing a bit more about the workaround you were using before you had this slot option?

**Comment by themeler** [comment]
Yes, you're right, I've left this accesibility issue for later consideration (second sprint let's call it :). I want to add it, but it's little bit complicated (not impossible tho :). I'll work on that.

**There are 2 issues bound to the use case.**

1. You need to know what max items number is set (in practice, you'll set it even if is the same as default to be sure). Then, before appending custom list item to items, you'll need to cap your (probably fetched from server) items for suggestion list at `max items - 1`, to ensure that your custom suggestion will always be rendered (you may have 5/5 results, but still not what user wants). Then you'll need to add custom item at the end of fetched items (component sorting must be disabled of course). And that creates second thing issue...

2. While using Typescript, when you have items with defined interface, you'll always need to create locally new interface, for example, where only `name` is required (you'll take name from query). The rest must be optional. And then, while you have `hit` you'll need to check if id/uuid is missing, and if so, create new resource, before returning, proper item with an id/uuid that will match resource interface.

Hope I've explained this properly. This is a lot of hussle, which is resolved using custom slot with custom action, 

With this feature, you can just render items from server, as it is. And then, if you want, you can just render this custom slot, that will emit `hitListAppend`, calling for example `createResource` action, without any gymnastics :)

I'm used to [Vuetify](https://vuetifyjs.com/en/api/v-autocomplete/#slots), where this feature is present, but dont remember if it's accesible via keyboard (probably is :).

**Comment by mattzollinhofer** [comment]
Thanks for that write up, very helpful to understand. Let me think about that a bit. I’ve had a idea about allowing for a different data structure to be passed in and I wonder if that might help with this as well. The idea would be to note that a specific piece of data is for appending rather than providing a slot. 

It’s not fully formed yet though and having additional use cases like this helps.

**Comment by mattzollinhofer** [comment]
@themeler: I'm still thinking about this, but after working on the background variant request PR (#94) I'm thinking more about that model. Meaning, this typeahead component would look for information in the object of the data provided to support a feature like this. 

For example, when you provide `data` you could provide 
```[
  {
    id: 1
    text: 'red'
  }
  {
    id: 2
    text: 'blue'
  }
  {
    text: 'Add new color: purple'
    append: true
  }
]
```

Then the component could key on `append` as part of the data to pull it out of the sorting and append it to the end and fire an addition event for it.

I _think_ that feels a little better to me as an API and would then not necessitate additional accessibility efforts. The list being a unified thing feels like the right directions, but I'm just thinking out loud. 

Any thoughts on that idea?

**Pull request closed without merging**
