### PR TITLE
Update VueTypeaheadBootstrapList.vue

### PR DESCRIPTION
**Pull request by ttodua**
Without optimization, this plugin adds 500kb (complete lodash) to the app - https://i.imgur.com/DGhkWKo.png

So, this commit makes the import procedure as it needs to be done per standards. Please see section - Reducing size of lodash : https://medium.com/js-dojo/how-to-reduce-your-vue-js-bundle-size-with-webpack-3145bf5019b7

### CODE REVIEW

**Comment by mattzollinhofer** [comment]
@ttodua, this looks great, thanks for the PR!

I'm hoping to have some time to look at this project today. I need to get the tests passing again and then I'll take a look at this. If all goes well I might be able to merge today, but no promises 😀

**Comment by mattzollinhofer** [comment]
Before this PR
```
 DONE  Compiled successfully in 8299ms                                                     3:41:32 PM

  File                                     Size             Gzipped

  dist/VueTypeaheadBootstrap.umd.min.js    108.31 KiB       37.46 KiB
  dist/VueTypeaheadBootstrap.umd.js        640.58 KiB       122.37 KiB
  dist/VueTypeaheadBootstrap.common.js     640.18 KiB       122.25 KiB
  dist/VueTypeaheadBootstrap.css           0.34 KiB         0.22 KiB
```

After this PR
```
DONE  Compiled successfully in 3202ms                                                      3:41:03 PM

  File                                     Size             Gzipped

  dist/VueTypeaheadBootstrap.umd.min.js    67.07 KiB        21.51 KiB
  dist/VueTypeaheadBootstrap.umd.js        250.43 KiB       57.26 KiB
  dist/VueTypeaheadBootstrap.common.js     250.02 KiB       57.13 KiB
  dist/VueTypeaheadBootstrap.css           0.34 KiB         0.22 KiB

```

**Comment by mattzollinhofer** [comment]
This is resolved by #84. Thanks for submitting this! It forced me to get the tests and CI back in shape again which is good the project.

**Comment by mattzollinhofer** [comment]
https://www.npmjs.com/package/vue-typeahead-bootstrap

**Comment by ttodua** [comment]
Excellent Matt! Your dedication to maintain this repo is nice! I hope somehow more attraction should be passed from the original `alex's` repo to this. Also, you might add `Patreon/Github sponsor` for your repo, like nowadays other people have, which might give you some motivation too.

**Comment by ttodua** [comment]
after `npm i vue-typeahead-bootstrap` it creates 3 folder in `node_modules` : https://i.imgur.com/CjhO5eh.png
where "dist" and "dist-with-lodash" seems same.  How we can avoid that, and just use the "without-lodash" version into "dist"?

**Comment by mattzollinhofer** [comment]
So, I think the dist, dist-without-lodash, and dist-with-lodash were just a mistake on my part. I removed those and I think they'll be gone. 

I'm not sure about the devDependencies idea. It looks like the most recent change cause someone else a problem (#86) that I don't completely understand. I'm cutting a beta branch #87 to add lodash to proper dependencies to see if it helps them. Feel free to take a look at that PR.

**Pull request closed without merging**
