### PR TITLE
added inputType prop

### PR DESCRIPTION
**Pull request by bipin000**

### CODE REVIEW

**Comment by bipin000** [comment]
added inputType prop

**Comment by bipin000** [comment]
fix for issue #73

**Comment by mattzollinhofer** [comment]
Looks a like a good quality PR. I'm looking to get a little more feedback about the issue's use case. Feel free to respond with more detail on #73.

@bipin000, since you authored this PR I assumed you were the same person who submitted the issue. I realize that now that you were just being helpful, thanks!!

If you're interested in other issues that could help the project, this might be another one that isn't too hard to knock out #76.

**Comment by bipin000** [comment]
> Looks a like a good quality PR. I'm looking to get a little more feedback about the issue's use case. Feel free to respond with more detail on #73.
> 
> @bipin000, since you authored this PR I assumed you were the same person who submitted the issue. I realize that now that you were just being helpful, thanks!!
> 
> If you're interested in other issues that could help the project, this might be another one that isn't too hard to knock out #76.

Sure, I will try to fix this issue by next weekend

**Comment by mattzollinhofer** [comment]
Closing for now while waiting for a response to the issue, will re-open if we decide to move forward with this work. Thanks!

**Pull request closed without merging**
